# Generated by Django 5.0 on 2024-03-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
